# Tell Travis what to do
# https://travis-ci.org/nedbat/coveragepy

language: python

python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

install:
  - python setup.py clean develop
  #- python igor.py zip_mods install_egg remove_extension

script:
  #- python setup.py clean develop
  - python igor.py zip_mods install_egg
  - python igor.py test_with_tracer c
  - python igor.py remove_extension
  - python igor.py test_with_tracer py
