# Tell Travis what to do
# https://travis-ci.com/nedbat/coveragepy

dist: xenial
language: python

cache: pip
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - 'pypy2.7-6.0'
  - 'pypy3.5-6.0'

env:
  matrix:
    - COVERAGE_COVERAGE=no
    - COVERAGE_COVERAGE=yes

install:
  - pip install -r requirements/ci.pip
  - pip freeze

script:
  - tox
  - if [[ $COVERAGE_COVERAGE == 'yes' ]]; then python igor.py combine_html; fi
  - if [[ $COVERAGE_COVERAGE == 'yes' ]]; then pip install codecov; fi
  - if [[ $COVERAGE_COVERAGE == 'yes' ]]; then codecov -X gcov --file coverage.xml; fi
